apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: idp-demo-app
spec:
  id: idp-demo-app
  parameters:
    namespace: production
    image: docker.io/vfarcic/idp-demo-app:0.0.0
    host: acme.com
  compositionSelector:
    matchLabels:
      type: backend-db-local
